import type { Metadata } from 'next';
import { Bowlby_One_SC, DM_Mono } from 'next/font/google';

import './globals.css';
import Header from './components/Header';
import { SVGFilters } from './components/SVGFilters';
import { Footer } from './components/Footer';

const bowlbyOne = Bowlby_One_SC({
	subsets: ['latin'],
	variable: '--font-bowlby-sc',
	display: 'swap',
	weight: '400',
});

const dmMono = DM_Mono({
	subsets: ['latin'],
	variable: '--font-dm-mono',
	display: 'swap',
	weight: '500',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${bowlbyOne.variable} ${dmMono.variable} antialiased font-mono text-zinc-800 font-medium`}>
				<main>
					<Header></Header>
					{children}
					<Footer></Footer>
				</main>

				<SVGFilters />
			</body>
		</html>
	);
}
